### ISSUE TITLE
Sm4加密方式mode配置

### ISSUE THREAD

**Issue by Secretlovez** [byte-fe/gm-crypto#9]
在参考示例中，sm4的mode配置使用了SM2.constants.CBC配置。但在实际运行中，这个SM2.constants.CBC是不存在的，配置了SM2.constants.CBC的sm4 cbc模式加解密生效了

**Comment by Secretlovez** [comment]
![image](https://user-images.githubusercontent.com/40491055/164405542-5e78cf55-16d3-4294-85b5-e7ad65e2521b.png)

**Comment by panjizhi** [comment]
readme 中的实例写错了，fix #13
